apiVersion: v1
kind: Secret
metadata:
  name: websphere-cafe-secret
  namespace: websphere-cafe
type: Opaque
data:
  DB_USER: Y2FmZQ==      # base64 encoded 'cafe'
  DB_PASSWORD: Y2FmZTEyMw==  # base64 encoded 'cafe123'