<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<parent>
		<artifactId>websphere-cafe-modules</artifactId>
		<groupId>websphere-cafe</groupId>
		<version>0.1-SNAPSHOT</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<artifactId>websphere-cafe-web</artifactId>
	<packaging>war</packaging>
	<name>${project.artifactId}</name>

	<description>This is the basic Java EE application used throughout the WebSphere on Azure demos.
        It is a simple CRUD application. It uses Maven and Java EE 7 (JAX-RS, EJB, CDI, JPA, JSF, Bean Validation).
        Migrated to OpenLiberty for Kubernetes deployment.
    </description>

	<dependencies>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>42.6.0</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.microprofile</groupId>
			<artifactId>microprofile</artifactId>
			<version>6.0</version>
			<type>pom</type>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<finalName>websphere-cafe</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<source>11</source>
					<target>11</target>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.2.2</version>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
				</configuration>
			</plugin>
			<plugin>
				<groupId>io.openliberty.tools</groupId>
				<artifactId>liberty-maven-plugin</artifactId>
				<version>3.8.2</version>
				<configuration>
					<serverName>websphere-cafe</serverName>
					<bootstrapProperties>
						<default.http.port>9080</default.http.port>
						<default.https.port>9443</default.https.port>
					</bootstrapProperties>
					<copyDependencies>
						<location>${project.build.directory}/liberty/wlp/usr/shared/config/lib</location>
						<dependency>
							<groupId>org.postgresql</groupId>
							<artifactId>postgresql</artifactId>
						</dependency>
					</copyDependencies>
				</configuration>
				<executions>
					<execution>
						<id>package-server</id>
						<phase>package</phase>
						<goals>
							<goal>create</goal>
							<goal>install-apps</goal>
							<goal>package</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>